### ISSUE TITLE
Broken in latest rails version 5.1.0.beta1

### ISSUE THREAD

**Issue by jonhue** [charlotte-ruby/impressionist#234]
> c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/impressionist-1.5.2/app/controllers/impressionist_controller.rb:12:in `included': undefined method `before_filter' for ActionController::Base:Class (NoMethodError)
Did you mean?  before_action

`before_filter` has been removed in rails 5.1

**Comment by johnmcaliley** [comment]
@jonhue my only concern about this is supporting rails 3, but at this point I think they will just have to freeze the gem version if they are on rails 3.  I'm considering bumping up to version 2.0.0 for this since it is a breaking change for rails 3 users.  I'll go ahead and merge it into master and start working on publishing the new version.  Also, If you have any interest in helping maintain this repository let me know and I'll give you write access and credentials to publish the gem.  I have very little time to maintain this project right now.

**Comment by fwolfst** [comment]
iiuc this fork is the most developed version of impressionist and looking for a maintainer? I ask not because I have the resources available to maintain or support impressionist, but because I was considering using it for a fresh-ish project.

**Comment by rchrand** [comment]
We have started – although slowly – to make a proper build in #238, and plan on continuing the support. Until this gets merged along with Rails 5.1 support, you are free to use one of the many branches that fixes the 5.1 problem.

@fwolfst We have used Impressionist in production for quite some time now, and haven't run into a single problem yet.

**Comment by msimonborg** [comment]
I think #241 should close this issue, right?

**Comment by rchrand** [comment]
Yes! Thank you
